package xinboshin.thaumicwind.common;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import xinboshin.thaumicwind.api.back.IModProxy;
import xinboshin.thaumicwind.api.back.IProxy;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.Mod.Metadata;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@Mod(modid = ThaumicWind.ID,
name = ThaumicWind.NAME,
version = ThaumicWind.VERSION,
acceptedMinecraftVersions = "[1.12.2]",
guiFactory = "xinboshin.thaumicwind.client.gui.config.ConfigGuiFactory")
public class ThaumicWind implements IModProxy {

	public static final String ID = "thaumicwind";
	public static final String NAME = "ThaumicWind";
	public static final String VERSION = "$version";
	public static final String SERVER_PROXY = "xinboshin.thaumicwind.common.CommonProxy";
	public static final String CLIENT_PROXY = "xinboshin.thaumicwind.client.ClientProxy";
	public static final Logger LOG = LogManager.getLogger(NAME);
	public static final CreativeTabs TAB = new CreativeTabs(Magistics.ID) {

		@Override
		public boolean hasSearchBar() {
			return true;
		}

		@Override
		@SideOnly(Side.CLIENT)
		public ItemStack getIconItemStack() {
			return new ItemStack(Items.NETHER_STAR, 1, 0);
		}

		@Override
		@SideOnly(Side.CLIENT)
		public ItemStack getTabIconItem() {
			return getIconItemStack();
		}
	};

	@Instance(ID)
	public static Magistics instance;

	@SidedProxy(serverSide = SERVER_PROXY, clientSide = CLIENT_PROXY)
	public static IProxy proxy;

	@Metadata
	private ModMetadata meta;

	@EventHandler
	@Override
	public void preInit(FMLPreInitializationEvent event) {
		meta.authorList.add("Xinboshin");
		meta.autogenerated = false;
		meta.credits = "Thanks to everyone who kept believing!";
		meta.description = "Logistical magic!";
		meta.logoFile = "logo.png";
		meta.modId = ID;
		meta.name = NAME;
		meta.url = "https://github.com/Xinboshin/ThaumicWind";
		meta.useDependencyInformation = false;
		meta.version = VERSION;
		proxy.preInit(event);
	}

	@EventHandler
	@Override
	public void init(FMLInitializationEvent event) {
		proxy.init(event);
	}

	@EventHandler
	@Override
	public void postInit(FMLPostInitializationEvent event) {
		proxy.postInit(event);
	}

	static {
		TAB.setBackgroundImageName("magistics.png").setNoTitle();
	}
}
